/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author S Siva Arunachalam
 */
public class EventOrganizerMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu1
     */
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public String add1;
    public String s1;
    public String s2;
    public String s3;
    public String s5;
    public EventOrganizerMainMenu() {
        Login m=new Login();
        add1=m.s1;
        initComponents();
    }
    public void get1(String s)
    {
        s5=s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        myprofileButton = new javax.swing.JButton();
        myeventButton = new javax.swing.JButton();
        publisheventButton = new javax.swing.JButton();
        attendedataButton = new javax.swing.JButton();
        studsno = new javax.swing.JLabel();
        noofstud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setMinimumSize(new java.awt.Dimension(1553, 813));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setMinimumSize(new java.awt.Dimension(1553, 813));
        jPanel6.setPreferredSize(new java.awt.Dimension(1553, 813));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(102, 239, 243));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(1553, 96));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Event Management System");
        jLabel1.setToolTipText("");

        logoutButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/logout.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setToolTipText("click here to logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(318, 318, 318)
                .addComponent(logoutButton)
                .addGap(52, 52, 52))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(225, 1000));

        myprofileButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        myprofileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Add.png"))); // NOI18N
        myprofileButton.setText("My Profile");
        myprofileButton.setToolTipText("");
        myprofileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myprofileButtonActionPerformed(evt);
            }
        });

        myeventButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        myeventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Add.png"))); // NOI18N
        myeventButton.setText("My Event");
        myeventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myeventButtonActionPerformed(evt);
            }
        });

        publisheventButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        publisheventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Search.png"))); // NOI18N
        publisheventButton.setText("Publish Event");
        publisheventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisheventButtonActionPerformed(evt);
            }
        });

        attendedataButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        attendedataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Search.png"))); // NOI18N
        attendedataButton.setText("Attendee Data");
        attendedataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendedataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(attendedataButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(publisheventButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myprofileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myeventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(myprofileButton)
                .addGap(18, 18, 18)
                .addComponent(myeventButton)
                .addGap(18, 18, 18)
                .addComponent(publisheventButton)
                .addGap(18, 18, 18)
                .addComponent(attendedataButton)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        studsno.setBackground(new java.awt.Color(0, 0, 0));
        studsno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        studsno.setForeground(new java.awt.Color(255, 255, 255));
        studsno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                studsnoMouseMoved(evt);
            }
        });

        noofstud.setBackground(new java.awt.Color(0, 0, 0));
        noofstud.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        noofstud.setForeground(new java.awt.Color(0, 51, 255));
        noofstud.setText("No. of Attendees Registered");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noofstud)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(studsno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(noofstud, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studsno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 1553, 813);
        jPanel6.getAccessibleContext().setAccessibleParent(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1553, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Login login=new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void studsnoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studsnoMouseMoved
        // TODO add your handling code here:
        studsno.setText(s1);
    }//GEN-LAST:event_studsnoMouseMoved

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
                studsno.setText(s1);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        // TODO add your handling code here:
                studsno.setText(s1);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void myprofileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myprofileButtonActionPerformed
        // TODO add your handling code here:
        EventOrgInfo menu=new EventOrgInfo();
        this.hide();
        menu.setVisible(true);
    }//GEN-LAST:event_myprofileButtonActionPerformed

    private void myeventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myeventButtonActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Teacher ID already exists", "Error", JOptionPane.ERROR_MESSAGE);
        try{
            Login m=new Login();
            add1=m.s1;
            con = Connect.ConnectDB();
            String sql = "select * from events where EventOrgID='"+s5+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                this.hide();
                EventPublishForm teacher=new EventPublishForm();
                teacher.setVisible(true);
                String add14 = rs.getString("EventID");
                teacher.EventIDField.setText(add14);
                String add2 = rs.getString("EventName");
                teacher.EventNameField.setText(add2);
                String add3 = rs.getString("EventOrgID");
                teacher.EventOrganizerIDField.setText(add3);
                String add4 = rs.getString("EventOrgName");
                teacher.EventOrganizerNameField.setText(add4);
                String add5 = rs.getString("EventOrgPhNo");
                teacher.mobileField.setText(add5);
                String add6 = rs.getString("Description");
                teacher.DescriptionField.setText(add6);
                String add7 = rs.getString("Venue");
                teacher.Venuecmb.setSelectedItem(add7);
                String add8 = rs.getString("Date");
                java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(add8);
                teacher.setdate(date2);
                String add9 = rs.getString("StartTime");
                java.util.Date date1 = new SimpleDateFormat("HH:mm:ss").parse(add9);
                teacher.setstarttime(date1);
                String add12 = rs.getString("EndTime");
                java.util.Date date3 = new SimpleDateFormat("HH:mm:ss").parse(add12);
                teacher.setendtime(date3);
                String add10 = rs.getString("SeatAvailability");
                teacher.SeatAvailabilityField.setText(add10);
                String add11 = rs.getString("Email");
                teacher.EmailLabelField.setText(add11);
                teacher.updateButton.setEnabled(true);
                teacher.deleteButton.setEnabled(true);
                teacher.saveButton.setEnabled(false);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_myeventButtonActionPerformed

    private void publisheventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisheventButtonActionPerformed
        // TODO add your handling code here:
        EventPublishForm menu=new EventPublishForm();
        this.hide();
        menu.setVisible(true);
    }//GEN-LAST:event_publisheventButtonActionPerformed

    private void attendedataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendedataButtonActionPerformed
        // TODO add your handling code here:
        AttendeeRecord1 menu=new AttendeeRecord1();
        this.hide();
        menu.setVisible(true);
    }//GEN-LAST:event_attendedataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventOrganizerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventOrganizerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventOrganizerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventOrganizerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            EventOrganizerMainMenu mainmenu=new EventOrganizerMainMenu();
            mainmenu.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendedataButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myeventButton;
    private javax.swing.JButton myprofileButton;
    private javax.swing.JLabel noofstud;
    private javax.swing.JButton publisheventButton;
    private javax.swing.JLabel studsno;
    // End of variables declaration//GEN-END:variables

    private static class stud extends Component {

        public stud() {
        }
    }
}
