/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author S Siva Arunachalam
 */
public class EventInfo extends javax.swing.JFrame {

    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form TeacherForm1
     */
    public EventInfo() {
        initComponents();
    }
    void reset(){
        EventIDField.setText("");
        EventNameField.setText("");
        EventOrganizerIDField.setText("");
        EmailLabelField.setText("");
        mobileField.setText("");
        EventOrganizerNameField.setText("");
        DescriptionField.setText("");
        Venuecmb.setSelectedIndex(0);
        SeatAvailabilityField.setText("");
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
        EventIDField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EventIDLabel = new javax.swing.JLabel();
        EventIDField = new javax.swing.JTextField();
        EventNameLabel = new javax.swing.JLabel();
        EventNameField = new javax.swing.JTextField();
        EventOrganizerIDLabel = new javax.swing.JLabel();
        EventOrganizerIDField = new javax.swing.JTextField();
        EventOrganizerNameLabel = new javax.swing.JLabel();
        EventOrganizerNameField = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileField = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        SeatAvailabilityLabel = new javax.swing.JLabel();
        SeatAvailabilityField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailLabelField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        endtimeLabel = new javax.swing.JLabel();
        VenueLabel = new javax.swing.JLabel();
        Venuecmb = new javax.swing.JComboBox<>();
        DateChooser = new com.toedter.calendar.JDateChooser();
        starttimeTimeChooser = new lu.tudor.santec.jtimechooser.JTimeChooser();
        starttimeLabel = new javax.swing.JLabel();
        endtimeTimeChooser = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jPanel4 = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher Form");
        setMinimumSize(new java.awt.Dimension(1366, 700));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1666, 720));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                                   Teacher's Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Basic Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        EventIDLabel.setBackground(new java.awt.Color(0, 0, 0));
        EventIDLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EventIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventIDLabel.setText("EventID:");

        EventIDField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EventIDField.setToolTipText("Enter First Name here");
        EventIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventIDFieldActionPerformed(evt);
            }
        });
        EventIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EventIDFieldKeyTyped(evt);
            }
        });

        EventNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        EventNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EventNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventNameLabel.setText("Event Name:");
        EventNameLabel.setToolTipText("");

        EventNameField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EventNameField.setToolTipText("Enter Last Name Here");
        EventNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventNameFieldActionPerformed(evt);
            }
        });
        EventNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EventNameFieldKeyTyped(evt);
            }
        });

        EventOrganizerIDLabel.setBackground(new java.awt.Color(0, 0, 0));
        EventOrganizerIDLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EventOrganizerIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventOrganizerIDLabel.setText("Event Organizer ID:");

        EventOrganizerIDField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EventOrganizerIDField.setToolTipText("Enter Father's Name here");
        EventOrganizerIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventOrganizerIDFieldActionPerformed(evt);
            }
        });
        EventOrganizerIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EventOrganizerIDFieldKeyTyped(evt);
            }
        });

        EventOrganizerNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        EventOrganizerNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EventOrganizerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventOrganizerNameLabel.setText("Event Organizer Name:");

        EventOrganizerNameField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EventOrganizerNameField.setToolTipText("Enter Aadhar Number here");
        EventOrganizerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventOrganizerNameFieldActionPerformed(evt);
            }
        });
        EventOrganizerNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EventOrganizerNameFieldKeyTyped(evt);
            }
        });

        mobileLabel.setBackground(new java.awt.Color(0, 0, 0));
        mobileLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mobileLabel.setForeground(new java.awt.Color(255, 255, 255));
        mobileLabel.setText("Mobile Number: ");

        mobileField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        mobileField.setToolTipText("Enter Father's Mobile Number here");
        mobileField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileFieldKeyTyped(evt);
            }
        });

        DescriptionLabel.setBackground(new java.awt.Color(0, 0, 0));
        DescriptionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DescriptionLabel.setText("Description:");

        DescriptionField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        DescriptionField.setToolTipText("EnterStudent's Address here");
        DescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionFieldActionPerformed(evt);
            }
        });

        SeatAvailabilityLabel.setBackground(new java.awt.Color(0, 0, 0));
        SeatAvailabilityLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SeatAvailabilityLabel.setForeground(new java.awt.Color(255, 255, 255));
        SeatAvailabilityLabel.setText("Seat Availability:");

        SeatAvailabilityField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        SeatAvailabilityField.setToolTipText("Enter Student's Date of Birth here");
        SeatAvailabilityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatAvailabilityFieldActionPerformed(evt);
            }
        });

        EmailLabel.setBackground(new java.awt.Color(0, 0, 0));
        EmailLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email Address:");

        EmailLabelField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EmailLabelField.setToolTipText("Enter Father's Phone Number here");
        EmailLabelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailLabelFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(EventOrganizerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EventIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EventOrganizerIDLabel)
                                    .addComponent(SeatAvailabilityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(SeatAvailabilityField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mobileLabel)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(170, 170, 170)
                                                .addComponent(EventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mobileField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EventOrganizerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EventIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EventNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EventOrganizerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(361, 361, 361)))))
                        .addGap(180, 180, 180))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel)
                            .addComponent(DescriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DescriptionField)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EmailLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventOrganizerIDLabel)
                    .addComponent(EventOrganizerNameLabel)
                    .addComponent(EventOrganizerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventOrganizerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileLabel)
                    .addComponent(mobileField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatAvailabilityLabel)
                    .addComponent(SeatAvailabilityField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Education & Experience", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        DateLabel.setBackground(new java.awt.Color(0, 0, 0));
        DateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setText("Date:");

        endtimeLabel.setBackground(new java.awt.Color(0, 0, 0));
        endtimeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        endtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        endtimeLabel.setText("End Time:");

        VenueLabel.setBackground(new java.awt.Color(0, 0, 0));
        VenueLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VenueLabel.setForeground(new java.awt.Color(255, 255, 255));
        VenueLabel.setText("Venue:");

        Venuecmb.setBackground(new java.awt.Color(102, 102, 102));
        Venuecmb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Venuecmb.setForeground(new java.awt.Color(255, 255, 255));
        Venuecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "S&H Seminar Hall", "Civil Seminar Hall", "Mechanical Seminar Hall", "CSE Seminar Hall", "ECE Seminar Hall", "BioTech Seminar Hall" }));

        DateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateChooserMouseClicked(evt);
            }
        });
        DateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DateChooserKeyTyped(evt);
            }
        });

        starttimeTimeChooser.setToolTipText("HH:MM:SS");
        starttimeTimeChooser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        starttimeTimeChooser.setName(""); // NOI18N

        starttimeLabel.setBackground(new java.awt.Color(0, 0, 0));
        starttimeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        starttimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        starttimeLabel.setText("Start Time:");

        endtimeTimeChooser.setToolTipText("HH:MM:SS");
        endtimeTimeChooser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        endtimeTimeChooser.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Venuecmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(420, 420, 420)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(starttimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(endtimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(starttimeTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endtimeTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(547, 547, 547))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(starttimeTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(starttimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Venuecmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(endtimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(endtimeTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        newButton.setBackground(new java.awt.Color(102, 102, 102));
        newButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newButton.setForeground(new java.awt.Color(255, 255, 255));
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(102, 102, 102));
        saveButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(102, 102, 102));
        updateButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(102, 102, 102));
        deleteButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(updateButton)
                .addGap(51, 51, 51)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backButton, deleteButton, newButton, saveButton, updateButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(newButton)
                    .addComponent(saveButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backButton, deleteButton, newButton, saveButton, updateButton});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventIDFieldActionPerformed

    private void EventNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventNameFieldActionPerformed

    private void EventOrganizerIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventOrganizerIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventOrganizerIDFieldActionPerformed

    private void DescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionFieldActionPerformed

    private void SeatAvailabilityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatAvailabilityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatAvailabilityFieldActionPerformed

    private void EmailLabelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailLabelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailLabelFieldActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        reset();
    }//GEN-LAST:event_newButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        EventOrganizerMainMenu menu=new EventOrganizerMainMenu();
        this.hide();
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        try{
            con = Connect.ConnectDB();
            if("".equals(EventIDField.getText())){
                JOptionPane.showMessageDialog(null, "Please Enter Teacher ID", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Statement st;
            st = con.createStatement();
            String sql1="select EventID from Events where EventID='"+EventIDField.getText()+"'";
            rs = st.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Teacher ID already exists", "Error", JOptionPane.ERROR_MESSAGE);
                EventIDField.setText("");
                EventIDField.requestDefaultFocus();
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(DateChooser.getDate().getTime());
            String sql= "insert into Events(`EventID`, `EventName`, `EventOrgID`, `EventOrgName`, `EventOrgPhNo`, `Description`, `Venue`, `Date`, `StartTime`, `EndTime`, `SeatAvailability`, `Email`)values('"+EventIDField.getText()+"','"+EventNameField.getText()+"','"+EventOrganizerIDField.getText()+"','"+EventOrganizerNameField.getText()+"','"+mobileField.getText()+"','"+DescriptionField.getText()+"','"+Venuecmb.getSelectedItem()+"','"+dob+"','"+starttimeTimeChooser.getFormatedTime()+"','"+endtimeTimeChooser.getFormatedTime()+"','"+SeatAvailabilityField.getText()+"','"+EmailLabelField.getText()+"')";
            pst = con.prepareStatement(sql);
            pst.execute();
            String sql2= "insert into eventorganizerrecord(EventID,SeatAvailability)values('" + EventIDField.getText() + "','" + SeatAvailabilityField.getText() + "')";
            pst=con.prepareStatement(sql2);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Registered!", "Teacher", JOptionPane.INFORMATION_MESSAGE);
            saveButton.setEnabled(false);
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try{
            con = Connect.ConnectDB();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(DateChooser.getDate().getTime());
            String sql = "update events set EventID='"+EventIDField.getText()+"',EventName='"+EventNameField.getText()+"',EventOrgID='"+EventOrganizerIDField.getText()+"',EventOrgName='"+EventOrganizerNameField.getText()+"',EventOrgPhNo='"+mobileField.getText()+"',Description='"+DescriptionField.getText()+"',Venue='"+Venuecmb.getSelectedItem()+"',Date='"+dob+"',StartTime='"+starttimeTimeChooser.getFormatedTime()+"',EndTime='"+endtimeTimeChooser.getFormatedTime()+"',SeatAvailability='"+ SeatAvailabilityField.getText()+"',Email='"+EmailLabelField.getText()+"'where EventID='"+EventIDField.getText()+"'";
            pst = con.prepareStatement(sql);
            pst.execute();
            if("".equals(EventIDField.getText())){
                JOptionPane.showMessageDialog(null, "Please select a record to update!");
                return;
            }
            JOptionPane.showMessageDialog(this, "Updated Successfully!","Record",JOptionPane.INFORMATION_MESSAGE);
            updateButton.setEnabled(false);
        }
        catch(HeadlessException | SQLException ex){

            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try{
            if("".equals(EventIDField.getText())){
                JOptionPane.showMessageDialog(null, "Please enter Teacher ID to delete record!");
                return;
            }
            int d = JOptionPane.showConfirmDialog(this, "Are sure want to delete.?", "Confirmation", JOptionPane.YES_NO_OPTION);

            if(d==0){
                con = Connect.ConnectDB();
                String sql = "delete from events where EventID='"+EventIDField.getText()+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this,"Successfully deleted","Record",JOptionPane.INFORMATION_MESSAGE);
                reset();
            }

        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void mobileFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileFieldKeyTyped
        char input = evt.getKeyChar();
         if((input<'0' || input>'9') && input!='\b'){
             evt.consume();
             JOptionPane.showMessageDialog(this, "Please enter digits!");
         }
    }//GEN-LAST:event_mobileFieldKeyTyped

    private void EventOrganizerNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EventOrganizerNameFieldKeyTyped
        char input = evt.getKeyChar();
         if(!(input<'0' || input>'9') && input!='\b'){
             evt.consume();
             JOptionPane.showMessageDialog(this, "Name does not contain any numbers!");
         }
    }//GEN-LAST:event_EventOrganizerNameFieldKeyTyped

    private void EventIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EventIDFieldKeyTyped
        char input = evt.getKeyChar();
         if((input<'0' || input>'9') && input!='\b'){
             evt.consume();
             JOptionPane.showMessageDialog(this, "Please enter digits!");
         }
    }//GEN-LAST:event_EventIDFieldKeyTyped

    private void EventOrganizerIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EventOrganizerIDFieldKeyTyped
        char input = evt.getKeyChar();
         if((input<'0' || input>'9') && input!='\b'){
             evt.consume();
             JOptionPane.showMessageDialog(this, "Please enter digits!");
         }
    }//GEN-LAST:event_EventOrganizerIDFieldKeyTyped

    private void EventNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EventNameFieldKeyTyped
        char input = evt.getKeyChar();
         if(!(input<'0' || input>'9') && input!='\b'){
             evt.consume();
             JOptionPane.showMessageDialog(this, "Name does not contain any numbers!");
         }
    }//GEN-LAST:event_EventNameFieldKeyTyped

    private void EventOrganizerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventOrganizerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventOrganizerNameFieldActionPerformed

    private void DateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateChooserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateChooserMouseClicked

    private void DateChooserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateChooserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DateChooserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EventInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JLabel DateLabel;
    public javax.swing.JTextField DescriptionField;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel EmailLabel;
    public javax.swing.JTextField EmailLabelField;
    public javax.swing.JTextField EventIDField;
    private javax.swing.JLabel EventIDLabel;
    public javax.swing.JTextField EventNameField;
    private javax.swing.JLabel EventNameLabel;
    public javax.swing.JTextField EventOrganizerIDField;
    private javax.swing.JLabel EventOrganizerIDLabel;
    public javax.swing.JTextField EventOrganizerNameField;
    private javax.swing.JLabel EventOrganizerNameLabel;
    public javax.swing.JTextField SeatAvailabilityField;
    private javax.swing.JLabel SeatAvailabilityLabel;
    private javax.swing.JLabel VenueLabel;
    public javax.swing.JComboBox<String> Venuecmb;
    private javax.swing.JButton backButton;
    public javax.swing.JButton deleteButton;
    private javax.swing.JLabel endtimeLabel;
    private lu.tudor.santec.jtimechooser.JTimeChooser endtimeTimeChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField mobileField;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JButton newButton;
    public javax.swing.JButton saveButton;
    private javax.swing.JLabel starttimeLabel;
    private lu.tudor.santec.jtimechooser.JTimeChooser starttimeTimeChooser;
    public javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
